// <auto-generated />
using System;
using HRWorkForceSystemBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRWorkForceSystemBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250710082541_FinalInitialSetup")]
    partial class FinalInitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRWorkForceSystemBackend.Models.AuthModels.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("HRWorkForceSystemBackend.Models.AuthModels.HRUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("HRUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Engineering",
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            FullName = "John Doe",
                            LastName = "Doe",
                            PasswordHash = "hashed_password",
                            PhoneNumber = "",
                            Role = "Senior Developer",
                            UserName = "john.doe@example.com"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Engineering",
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            FullName = "Jane Smith",
                            LastName = "Smith",
                            PasswordHash = "hashed_password",
                            PhoneNumber = "",
                            Role = "Frontend Developer",
                            UserName = "jane.smith@example.com"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Quality Assurance",
                            Email = "peter.jones@example.com",
                            FirstName = "Peter",
                            FullName = "Peter Jones",
                            LastName = "Jones",
                            PasswordHash = "hashed_password",
                            PhoneNumber = "",
                            Role = "QA Engineer",
                            UserName = "peter.jones@example.com"
                        });
                });

            modelBuilder.Entity("HRWorkForceSystemBackend.Models.AuthModels.WorkforceUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkforceUsers");
                });

            modelBuilder.Entity("HRWorkForceSystemBackend.Models.ProjectsModels.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Migrating legacy backend to .NET Core.",
                            IsActive = true,
                            ProjectName = "E-commerce Backend Migration",
                            StartDate = new DateTime(2025, 7, 10, 8, 25, 40, 788, DateTimeKind.Utc).AddTicks(9127)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Building a new SPA using React.",
                            IsActive = true,
                            ProjectName = "New Customer Portal (React)",
                            StartDate = new DateTime(2025, 8, 9, 8, 25, 40, 788, DateTimeKind.Utc).AddTicks(9131)
                        });
                });

            modelBuilder.Entity("HRWorkForceSystemBackend.Models.ProjectsModels.ProjectSkillRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumberOfResourcesNeeded")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("RequiredProficiencyLevel")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProjectSkillRequirements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumberOfResourcesNeeded = 2,
                            ProjectId = 1,
                            RequiredProficiencyLevel = 4,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 2,
                            NumberOfResourcesNeeded = 2,
                            ProjectId = 1,
                            RequiredProficiencyLevel = 4,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 3,
                            NumberOfResourcesNeeded = 1,
                            ProjectId = 1,
                            RequiredProficiencyLevel = 3,
                            SkillId = 4
                        },
                        new
                        {
                            Id = 4,
                            NumberOfResourcesNeeded = 3,
                            ProjectId = 2,
                            RequiredProficiencyLevel = 4,
                            SkillId = 3
                        });
                });

            modelBuilder.Entity("HRWorkForceSystemBackend.Models.SkillgapModels.EmployeeSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SkillId");

                    b.ToTable("EmployeeSkills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            LastUpdated = new DateTime(2025, 7, 10, 8, 25, 40, 788, DateTimeKind.Utc).AddTicks(9173),
                            ProficiencyLevel = 5,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 1,
                            LastUpdated = new DateTime(2025, 7, 10, 8, 25, 40, 788, DateTimeKind.Utc).AddTicks(9174),
                            ProficiencyLevel = 5,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 1,
                            LastUpdated = new DateTime(2025, 7, 10, 8, 25, 40, 788, DateTimeKind.Utc).AddTicks(9175),
                            ProficiencyLevel = 4,
                            SkillId = 4
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 2,
                            LastUpdated = new DateTime(2025, 7, 10, 8, 25, 40, 788, DateTimeKind.Utc).AddTicks(9177),
                            ProficiencyLevel = 5,
                            SkillId = 3
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 3,
                            LastUpdated = new DateTime(2025, 7, 10, 8, 25, 40, 788, DateTimeKind.Utc).AddTicks(9178),
                            ProficiencyLevel = 3,
                            SkillId = 5
                        });
                });

            modelBuilder.Entity("HRWorkForceSystemBackend.Models.SkillgapModels.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SkillName = "C#"
                        },
                        new
                        {
                            Id = 2,
                            SkillName = ".NET Core"
                        },
                        new
                        {
                            Id = 3,
                            SkillName = "React"
                        },
                        new
                        {
                            Id = 4,
                            SkillName = "SQL Server"
                        },
                        new
                        {
                            Id = 5,
                            SkillName = "Azure DevOps"
                        });
                });

            modelBuilder.Entity("HRWorkForceSystemBackend.Models.TrainingProgramModels.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainingProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingProgramId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("HRWorkForceSystemBackend.Models.TrainingProgramModels.TrainingProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TrainingPrograms");
                });

            modelBuilder.Entity("HRWorkForceSystemBackend.Models.WorkforceModels.Attrition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Attritions");
                });

            modelBuilder.Entity("HRWorkForceSystemBackend.Models.WorkforceModels.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("HRWorkForceSystemBackend.Models.WorkforceModels.Summary", b =>
                {
                    b.Property<int>("TotalAttritions")
                        .HasColumnType("int");

                    b.Property<int>("TotalExits")
                        .HasColumnType("int");

                    b.Property<int>("TotalPromotions")
                        .HasColumnType("int");

                    b.Property<int>("TotalTransfers")
                        .HasColumnType("int");

                    b.ToTable("Summaries");
                });

            modelBuilder.Entity("HRWorkForceSystemBackend.Models.ProjectsModels.ProjectSkillRequirement", b =>
                {
                    b.HasOne("HRWorkForceSystemBackend.Models.ProjectsModels.Project", "Project")
                        .WithMany("ProjectSkillRequirements")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRWorkForceSystemBackend.Models.SkillgapModels.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("HRWorkForceSystemBackend.Models.SkillgapModels.EmployeeSkill", b =>
                {
                    b.HasOne("HRWorkForceSystemBackend.Models.AuthModels.HRUser", "Employee")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRWorkForceSystemBackend.Models.SkillgapModels.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("HRWorkForceSystemBackend.Models.TrainingProgramModels.Enrollment", b =>
                {
                    b.HasOne("HRWorkForceSystemBackend.Models.TrainingProgramModels.TrainingProgram", "TrainingProgram")
                        .WithMany()
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("HRWorkForceSystemBackend.Models.AuthModels.HRUser", b =>
                {
                    b.Navigation("EmployeeSkills");
                });

            modelBuilder.Entity("HRWorkForceSystemBackend.Models.ProjectsModels.Project", b =>
                {
                    b.Navigation("ProjectSkillRequirements");
                });
#pragma warning restore 612, 618
        }
    }
}
